# Generated by Django 5.0.4 on 2024-04-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.IntegerField(choices=[(1, 'Enabled'), (0, 'Disabled')], db_index=True, default=1)),
                ('environment', models.IntegerField(choices=[(1, 'Global'), (2, 'Development'), (3, 'Production')], db_index=True, default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Created By')),
                ('updated_by', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Updated By')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Feature Toggle',
                'verbose_name_plural': 'Features Toggle',
                'db_table': 'feature_toggle',
                'ordering': ['-id'],
            },
        ),
    ]
